import { TutorialStep } from "./tutorial-overlay";

export const dashboardTutorialSteps: TutorialStep[] = [
  {
    id: "welcome",
    title: "Welcome to Healthcare RCM Dashboard",
    content: "Welcome! This interactive tutorial will guide you through the key features of your healthcare revenue cycle management dashboard. Let's get started by exploring the main navigation.",
    target: "[data-testid='navigation-header']",
    position: "bottom",
  },
  {
    id: "metrics-overview",
    title: "Dashboard Metrics",
    content: "This area displays your key performance indicators (KPIs) and metrics. You can see real-time data about revenue, collections, denials, and other important healthcare financial metrics.",
    target: "[data-testid='metrics-panel'], .metrics-panel, [class*='metric']",
    position: "right",
  },
  {
    id: "add-metrics",
    title: "Customize Your Dashboard",
    content: "Click this button to add or remove metrics from your dashboard. You can select from over 100+ standardized healthcare metrics to create a personalized view.",
    target: "[data-testid='button-add-metrics']",
    position: "bottom",
    action: "click",
  },
  {
    id: "metric-selection",
    title: "Metric Selection",
    content: "Here you can browse and select from canonical healthcare metrics. Use the search and filters to find specific metrics, then check the boxes to add them to your dashboard.",
    target: "[data-testid='metrics-list']",
    position: "left",
  },
  {
    id: "metric-filters",
    title: "Advanced Filtering",
    content: "Use these filters to narrow down metrics by domain (Revenue, Clinical, Operations), frequency (Daily, Monthly, Quarterly), and result type (Percentage, Currency, Count).",
    target: "[data-testid='button-toggle-filters']",
    position: "top",
    action: "click",
  },
  {
    id: "user-menu",
    title: "User Profile & Settings",
    content: "Access your user profile, role information, and account settings from this dropdown menu. You can also find development tools and logout options here.",
    target: "[data-testid='user-dropdown-trigger']",
    position: "bottom",
    action: "click",
  },
  {
    id: "demo-users",
    title: "Demo Environment",
    content: "Since this is a demo environment, you can switch between different user roles to see how the dashboard appears for various healthcare staff positions.",
    target: "[data-testid='link-demo-users']",
    position: "bottom",
    optional: true,
  },
  {
    id: "metric-cards",
    title: "Interactive Metric Cards",
    content: "Each metric card shows real-time data with trend indicators. Click on cards to see detailed views, and use the remove button (×) to customize your dashboard layout.",
    target: "[data-testid^='metric-card-'], .metric-card",
    position: "top",
  },
  {
    id: "dashboard-settings",
    title: "Dashboard Configuration",
    content: "Use this settings button to configure your dashboard layout, export your configuration, or reset to default settings. Your preferences are automatically saved.",
    target: "[data-testid='button-dashboard-settings']",
    position: "bottom",
    optional: true,
  },
  {
    id: "completion",
    title: "Tutorial Complete!",
    content: "Congratulations! You've completed the dashboard tutorial. You now know how to customize metrics, navigate the interface, and access key features. Start exploring your healthcare data!",
    target: "body",
    position: "top",
  },
];

export const metricPickerTutorialSteps: TutorialStep[] = [
  {
    id: "metric-picker-intro",
    title: "Metric Selection Interface",
    content: "This is where you can browse and select from our library of standardized healthcare metrics. All metrics follow Health Catalyst's canonical data model.",
    target: "[data-testid='metrics-list']",
    position: "right",
  },
  {
    id: "search-metrics",
    title: "Search for Metrics",
    content: "Use the search box to quickly find specific metrics by name, description, or steward. Try searching for terms like 'revenue', 'denial', or 'collection'.",
    target: "[data-testid='input-search-metrics']",
    position: "bottom",
    action: "click",
  },
  {
    id: "filter-toggle",
    title: "Advanced Filters",
    content: "Click here to show advanced filtering options. You can filter by domain, frequency, result type, and regulatory requirements.",
    target: "[data-testid='button-toggle-filters']",
    position: "top",
    action: "click",
  },
  {
    id: "select-metrics",
    title: "Select Metrics",
    content: "Check the boxes next to metrics you want to add to your dashboard. You can select up to 12 metrics at once for optimal viewing.",
    target: "[data-testid^='checkbox-'], input[type='checkbox']",
    position: "left",
    action: "click",
  },
  {
    id: "metric-details",
    title: "Metric Information",
    content: "Each metric shows its name, description, steward, frequency, and regulatory status. This helps you understand what the metric measures and who maintains it.",
    target: "[data-testid^='metric-item-']",
    position: "right",
  },
];